// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonChampions.Data;

#nullable disable

namespace PokemonChampions.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428202537_AddUsageTeammates")]
    partial class AddUsageTeammates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PokemonChampions.Data.Entities.AbilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowdownId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedId");

                    b.HasIndex("ShowdownId")
                        .IsUnique();

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.AliasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AliasText")
                        .IsUnique();

                    b.ToTable("Alias");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSetting");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMegaStone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MegaStoneFor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowdownId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedId");

                    b.HasIndex("ShowdownId")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.LearnsetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("PokemonId", "MoveId", "Generation", "Method")
                        .IsUnique();

                    b.ToTable("Learnset");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.MoveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowdownId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedId");

                    b.HasIndex("ShowdownId")
                        .IsUnique();

                    b.ToTable("Move");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.PokemonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability0")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ability1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilityH")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDef")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseFormShowdownId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormatBans")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentGenStandard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMega")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowdownId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Type1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedId");

                    b.HasIndex("ShowdownId")
                        .IsUnique();

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatShowdownId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Pokepaste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Team");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.TeamMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsLegal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IvAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvSpe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegalityNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Move1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Move2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Move3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Move4")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nature")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PokemonShowdownId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpSpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMember");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageAbilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsagePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("StatsId");

                    b.ToTable("UsageAbility");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsagePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("StatsId");

                    b.ToTable("UsageItem");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageMoveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsagePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("StatsId");

                    b.ToTable("UsageMove");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageSpreadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpSpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsagePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StatsId");

                    b.ToTable("UsageSpread");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatShowdownId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RawCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatsMonth")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("UsagePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId", "FormatShowdownId", "StatsMonth", "Source")
                        .IsUnique();

                    b.ToTable("UsageStats");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageTeammateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeammateId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsagePct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StatsId");

                    b.HasIndex("TeammateId");

                    b.ToTable("UsageTeammate");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.LearnsetEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.MoveEntity", "Move")
                        .WithMany("Learnsets")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonChampions.Data.Entities.PokemonEntity", "Pokemon")
                        .WithMany("Learnsets")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.TeamMemberEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageAbilityEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.AbilityEntity", "Ability")
                        .WithMany("UsageEntries")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonChampions.Data.Entities.UsageStatsEntity", "Stats")
                        .WithMany("Abilities")
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageItemEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.ItemEntity", "Item")
                        .WithMany("UsageEntries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonChampions.Data.Entities.UsageStatsEntity", "Stats")
                        .WithMany("Items")
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageMoveEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.MoveEntity", "Move")
                        .WithMany("UsageEntries")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonChampions.Data.Entities.UsageStatsEntity", "Stats")
                        .WithMany("Moves")
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageSpreadEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.UsageStatsEntity", "Stats")
                        .WithMany("Spreads")
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageStatsEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.PokemonEntity", "Pokemon")
                        .WithMany("UsageStats")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageTeammateEntity", b =>
                {
                    b.HasOne("PokemonChampions.Data.Entities.UsageStatsEntity", "Stats")
                        .WithMany("Teammates")
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonChampions.Data.Entities.PokemonEntity", "Teammate")
                        .WithMany()
                        .HasForeignKey("TeammateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stats");

                    b.Navigation("Teammate");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.AbilityEntity", b =>
                {
                    b.Navigation("UsageEntries");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.ItemEntity", b =>
                {
                    b.Navigation("UsageEntries");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.MoveEntity", b =>
                {
                    b.Navigation("Learnsets");

                    b.Navigation("UsageEntries");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.PokemonEntity", b =>
                {
                    b.Navigation("Learnsets");

                    b.Navigation("UsageStats");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.TeamEntity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PokemonChampions.Data.Entities.UsageStatsEntity", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Items");

                    b.Navigation("Moves");

                    b.Navigation("Spreads");

                    b.Navigation("Teammates");
                });
#pragma warning restore 612, 618
        }
    }
}
